"""empty message

Revision ID: 75d4f0b1ddda
Revises: 
Create Date: 2020-03-18 12:28:14.010926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75d4f0b1ddda'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('referenceNumber', sa.String(length=12), nullable=False),
    sa.Column('step', sa.Integer(), nullable=False),
    sa.Column('paymentMode', sa.String(length=80), nullable=False),
    sa.Column('amount', sa.String(length=80), nullable=False),
    sa.Column('funderAcct', sa.String(length=80), nullable=False),
    sa.Column('oldFunderBalance', sa.String(length=80), nullable=False),
    sa.Column('newFunderBalance', sa.String(length=80), nullable=False),
    sa.Column('benefAcct', sa.String(length=80), nullable=False),
    sa.Column('oldBenefBalance', sa.String(length=80), nullable=False),
    sa.Column('newBenefBalance', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('referenceNumber')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    # ### end Alembic commands ###
