"""empty message

Revision ID: eed9ab23e39e
Revises: 75d4f0b1ddda
Create Date: 2020-03-18 12:59:52.993333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eed9ab23e39e'
down_revision = '75d4f0b1ddda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('fraudStatus', sa.Enum('normal', 'suspected', 'confirmed', 'dismissed', name='fraud_status'), nullable=True))
    op.add_column('transactions', sa.Column('prediction', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'prediction')
    op.drop_column('transactions', 'fraudStatus')
    # ### end Alembic commands ###
